# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/Girls-Coding-Day-Jekyll-blog-4"

# 网页的标题
title: "HER Story"
username: Miseng.K
# 网站副标题
description: "share your #HERstory "

abouther: "_Supported by UN WOMAN, UN DP, Coding girls club_"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
